workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
    NETLIFY_SITE_ID: '0ed3211f-886d-49a9-a07a-0acc164bc063'


stages:
  - build
  - test
  - deploy_review
  - deploy_staging
  - deploy_prod


build_website:
  image: node:22-alpine
  stage: build
  script: 
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

test_artifact:
  image: node:22-alpine
  stage: test
  script:
    - test -f build/index.html

unit_test:
  image: node:22-alpine
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

netlify_review:
  image: node:22-alpine
  stage: .pre
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  before_script:
    - npm install -g netlify-cli@20.1.1
    - apk add curl jq
    - apk add curl
    - mkdir build
    - echo "Test" >> build/index.html
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --dir build --json | tee deploy-result.json
    - REVIEW_URL=$(jq -r '.deploy_url' deploy-result.json)
    - echo $REVIEW_URL
    - curl $REVIEW_URL | grep 'GitLab'
    - netlify deploy --dir build --json

netlify_staging:
  image: node:22-alpine
  stage: deploy_staging
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install -g netlify-cli@20.1.1
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --alias staging --dir build
    - curl 'https://staging--kj-learn-gitlab.netlify.app' | grep "GitLab"


netlify_prod:
  image: node:22-alpine
  stage: deploy_prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install -g netlify-cli@20.1.1
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id $NETLIFY_SITE_ID"
    - netlify deploy --prod --dir build
    - curl -Is --fail 'https://kj-learn-gitlab.netlify.app'