

test_npm:
  image: node:22-alpine
  stage: build
  script: 
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

test_artifact:
  image: node:22-alpine
  stage: test
  script:
    - test -f build/index.html

unit_test:
  image: node:22-alpine
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

